name: Update README

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches: [ master, main ]
    paths:
      - '.github/workflows/update-readme.yml'

jobs:
  update-stats:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Stats Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate baomidou pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=baomidou&repo=mybatis-plus
          path: profile/mybatis-plus-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate baomidou doc pin card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: pin
          options: username=baomidou&repo=mybatis-plus-doc
          path: profile/mybatis-plus-doc-stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.repository_owner }}
          file: profile/trophy.svg
          theme: classic
          cols: -1
          rows: 10
          panel-size: 115
          margin-width: 10
          margin-height: 10
          no-background: false
          no-frame: false

      - name: Commit changes
        run: |
          git config user.name "D.Yang"
          git config user.email "koyangslash@gmail.com"
          git add profile/
          git commit -m "Update README" || exit 0
          git push
